Projet_ELMOHCINE_EZZERRIFI/Models/Client/ClientManager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Projet_ELMOHCINE_EZZERRIFI.Models.Client
{
    public class ClientManager
    {

        public static List<ClientModel> map(List<Customers> clients)
        {
            List<ClientModel> list = new List<ClientModel>();
            foreach (var item in clients) list.Add(new ClientModel(item));
            return list;
        }

    }
}

Projet_ELMOHCINE_EZZERRIFI/Models/Client/ClientModel.cs
using Projet_ELMOHCINE_EZZERRIFI.Models.Expanse;
using Projet_ELMOHCINE_EZZERRIFI.Models.Projet;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Projet_ELMOHCINE_EZZERRIFI.Models.Client
{
    public class ClientModel
    {

        [DisplayName("Id client : ")]
        public Guid Customer_ID { get; set; }
        [DisplayName("Nom, Prénom :")][Required(ErrorMessage = "Champ obligatoire !")]
        public string Name { get; set; }
        [DisplayName("Code n° :")][Required(ErrorMessage = "Champ obligatoire !")][StringLength(10)]
        public string Code { get; set; }

        [DisplayName("Projet(s) : ")]
        public IEnumerable<ProjetModel> Projets { get; set; }
        [DisplayName("Expanse(s)")]
        public IEnumerable<ExpanseModel> Expanses { get; set; }


        public ClientModel()
        {
            this.Projets = new List<ProjetModel>();
            this.Expanses = new List<ExpanseModel>();
        }


        public ClientModel(Customers entite)
        {
            this.Customer_ID = entite.Customer_ID;
            this.Name = entite.Name;
            this.Code = entite.Code;

            if(entite.Expanses.Count() !=0 ) this.Expanses = from g in entite.Expanses select new ExpanseModel(g);
            if(!entite.Projects.Any()) this.Projets = from g in entite.Projects select new ProjetModel(g);
        }

    }
} 

Projet_ELMOHCINE_EZZERRIFI/Models/Client/ClientRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Projet_ELMOHCINE_EZZERRIFI.Models.Client
{
    public class ClientRepository
    {
        private NotesDeFraisEntities2 database { get; set; }

        public ClientRepository(NotesDeFraisEntities2 db)
        {
            this.database = db;
        }

        public List<Customers> GetAll()
        {
            return this.database.Customers.Include("Projects").Include("Expanses").ToList();
        }

        public void Delete(Guid id)
        {
            Customers client = this.database.Customers.Where(g => g.Customer_ID == id).FirstOrDefault();
            this.database.Customers.Remove(client);
            this.database.SaveChanges();
        }

        public void Add(Customers client)
        {
            this.database.Customers.Add(client);
            this.database.SaveChanges();
        }

        public Customers GetById(Guid id)
        {
            return this.database.Customers.Where(g => g.Customer_ID == id).FirstOrDefault();
        }

        public void Edit(Customers client)
        {
            Customers oldClient = this.database.Customers.Where(g => g.Customer_ID == client.Customer_ID).FirstOrDefault();

            oldClient.Name = client.Name;
            oldClient.Code = client.Code;

            this.database.SaveChanges();

        }

        public List<Projects> GetAllPojects(Guid id)
        {
            return this.database.Projects.Where(g => g.Customer_ID == id).ToList();
        }


    }
}

Projet_ELMOHCINE_EZZERRIFI/Controllers/ClientController.cs
using Projet_ELMOHCINE_EZZERRIFI.Models;
using Projet_ELMOHCINE_EZZERRIFI.Models.Client;
using Projet_ELMOHCINE_EZZERRIFI.Models.Projet;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projet_ELMOHCINE_EZZERRIFI.Controllers
{
    public class ClientController : Controller
    {

        public ActionResult List()
        {
            using (var dao = new NotesDeFraisEntities2())
            {
                ClientRepository CustRepo = new ClientRepository(dao);
                ProjetRepository ProjRepo = new ProjetRepository(dao);

                IEnumerable<ClientModel> ListClients = from g in CustRepo.GetAll() select new ClientModel(g);


                List<ClientModel> list = new List<ClientModel>();

                foreach (var client in ListClients)
                {

                    client.Projets = from g in CustRepo.GetAllPojects(client.Customer_ID) select new ProjetModel(g);

                    list.Add(client);
                }


                return View("List", list);
            }
        }

        public ActionResult Delete(Guid id)
        {
            using (var dao = new NotesDeFraisEntities2())
            {
                ClientRepository CustRepo = new ClientRepository(dao);

                CustRepo.Delete(id);
            }

            return RedirectToAction("List");
        }

        public ActionResult Create()
        {
            using (var dao = new NotesDeFraisEntities2())
            {
                ProjetRepository ProjRepo = new ProjetRepository(dao);

                ViewData["projets"] = from g in ProjRepo.GetAll() select new ProjetModel(g);
            }
            return View("Create");
        }

        [HttpPost]
        public ActionResult createAction(ClientModel newClient)
        {

            Customers client = new Customers();

            client.Customer_ID = Guid.NewGuid();
            client.Name = newClient.Name;
            client.Code = newClient.Code;

            using (var dao = new NotesDeFraisEntities2())
            {
                ClientRepository CustRepo = new ClientRepository(dao);
                CustRepo.Add(client);
            }
            return RedirectToAction("List");
        }

        public ActionResult Edit(Guid Customer_ID)
        {

            using(var dao = new NotesDeFraisEntities2())
            {
                ClientRepository custRepo = new ClientRepository(dao);

                ClientModel client = new ClientModel(custRepo.GetById(Customer_ID));

                return View("Edit", client);
            }
        }

        public ActionResult EditAction(ClientModel customer)
        {
            using(var dao = new NotesDeFraisEntities2())
            {
                ClientRepository custRepo = new ClientRepository(dao);

                Customers client = new Customers();

                client.Customer_ID = customer.Customer_ID;
                client.Name = customer.Name;
                client.Code = customer.Code;

                custRepo.Edit(client);
            }
            return RedirectToAction("List");
        }

        public ActionResult Details(Guid Customer_ID)
        {
            using(var dao = new NotesDeFraisEntities2()){
                ClientRepository custRepo = new ClientRepository(dao);
                ProjetRepository projRepo = new ProjetRepository(dao);

                ClientModel theCust = new ClientModel(custRepo.GetById(Customer_ID));
                theCust.Projets = from g in projRepo.GetByCustomer(theCust.Customer_ID) select new ProjetModel(g);
                return View("Details", theCust);
            }


        }




        }
}

Projet_ELMOHCINE_EZZERRIFI/Views/Client/Create.cshtml
@model Projet_ELMOHCINE_EZZERRIFI.Models.Client.ClientModel

@{
    ViewBag.Title = "Create";
}

<h2>Nouveau client</h2>

@using (Html.BeginForm("CreateAction","Client",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "List")
</div>

Projet_ELMOHCINE_EZZERRIFI/Views/Client/Details.cshtml
@model Projet_ELMOHCINE_EZZERRIFI.Models.Client.ClientModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ClientModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Projets)
        </dt>

        <dd>
            @if (Model.Projets != null)
            {
                foreach (var projet in Model.Projets)
                {
                        <text> - </text> @projet.Name;
                        <br />
                }
            }
                @Html.ActionLink("+ Nouveau projet","Create","Projet")

        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { Customer_ID = Model.Customer_ID }) |
    @Html.ActionLink("retour à la list", "List")
</p>

Projet_ELMOHCINE_EZZERRIFI/Views/Client/Edit.cshtml
@model Projet_ELMOHCINE_EZZERRIFI.Models.Client.ClientModel

@{
    ViewBag.Title = "Modifier un client";
}

<h2>Modifier client</h2>

@using (Html.BeginForm("EditAction", "Client", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClientModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
                @Html.HiddenFor(model => model.Customer_ID, new { htmlAttributes = new { @class = "form-control" } })
         
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la list", "List")
</div>

Projet_ELMOHCINE_EZZERRIFI/Views/Client/List.cshtml
@model IEnumerable<Projet_ELMOHCINE_EZZERRIFI.Models.Client.ClientModel>

@{
    ViewBag.Title = "List des clients";
}

<h2>List des clients</h2>

<p>
    @Html.ActionLink("Nouveau client", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Projets)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
                @foreach (var projet in item.Projets)
                {
                    <text>- </text>@projet.Name
                    if (projet.Project_ID != item.Projets.Last().Project_ID)
                    { <br />}
                }
                @if (item.Projets.Count() == 0)
                {
                    @Html.ActionLink("+ Nouveau projet", "../Projet/Create")
                }
            
        </td>
        <td>
            @Html.ActionLink("Détails", "Details", new { @item.Customer_ID }) |
            @Html.ActionLink("Modifier", "Edit", new { @item.Customer_ID  }) |
            <a onclick="return (confirm('Etes-vous sûr de vouloir supprimer cet élément ?'));" href="Delete/@item.Customer_ID">Supprimer</a>
        </td>
    </tr>
}

</table>