Projet_ELMOHCINE_EZZERRIFI/Models/Projet/ProjetManager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Projet_ELMOHCINE_EZZERRIFI.Models.Projet
{
    public class ProjetManager
    {
 
        public static List<ProjetModel> map(List<Projects> projets)
        {
            List<ProjetModel> list = new List<ProjetModel>();
            foreach (var item in projets) list.Add(new ProjetModel(item));
            return list;
        }
        public static List<Projects> map(List<ProjetModel> projets)
        {
            List<Projects> list = new List<Projects>();
            return list;
        }
    }
}

Projet_ELMOHCINE_EZZERRIFI/Models/Projet/ProjetModel.cs
using Projet_ELMOHCINE_EZZERRIFI.Models.Client;
using Projet_ELMOHCINE_EZZERRIFI.Models.Expanse;
using Projet_ELMOHCINE_EZZERRIFI.Models.Pole;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Projet_ELMOHCINE_EZZERRIFI.Models.Projet
{
    public class ProjetModel
    {

        public Guid Project_ID { get; set; }
        [DisplayName("Nom : ")][Required(ErrorMessage = "Champ obligatoire !")]
        public string Name { get; set; }
        [DisplayName("Desctiption : ")]
        public string Description { get; set; }
        [DisplayName("Budget : ")]
        public double Budget { get; set; }
        [DisplayName("Client : ")][Required(ErrorMessage = "Champ obligatoire !")]
        public Guid Customer_ID { get; set; }
        [DisplayName("Pôle : ")][Required(ErrorMessage = "Champ obligatoire !")]
        public Guid Pole_ID { get; set; }

        public virtual ClientModel Client { get; set; }
        public virtual PoleModel Poles { get; set; }

        [DisplayName("Expanse(s)")]
        public virtual IEnumerable<ExpanseModel> Expanses { get; set; }

        public ProjetModel()
        {
            this.Expanses = new List<ExpanseModel>();
        }

        public ProjetModel(Projects entite)
        {
            this.Project_ID = entite.Project_ID;
            this.Name = entite.Name;
            this.Description = entite.Description;
            this.Budget = entite.Budget;
            this.Customer_ID = entite.Customer_ID;
            this.Pole_ID = entite.Pole_ID;

            if (entite.Customers != null) this.Client = new ClientModel(entite.Customers);
            //if (entite.Poles != null) this.Poles = new PoleModel(entite.Poles);
            //if (entite.Expanses != null) this.Expanses = from g in entite.Expanses select new ExpanseModel(g);

        }
        
    }
}

Projet_ELMOHCINE_EZZERRIFI/Models/Projet/ProjetRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Projet_ELMOHCINE_EZZERRIFI.Models.Projet
{
    public class ProjetRepository
    {
        private NotesDeFraisEntities2 database { get; set; }

        public ProjetRepository(NotesDeFraisEntities2 db)
        {
            this.database = db;
        }
       
        public List<Projects> GetAll()
        {
            return this.database.Projects.Include("Customers").Include("Expanses").Include("Poles").ToList();
        }

        public void Add(Projects projet)
        {
            this.database.Projects.Add(projet);
            this.database.SaveChanges();
        }

        public Projects GetById(Guid id)
        {
            return this.database.Projects.Where(g => g.Project_ID == id).FirstOrDefault();
        }

        public void Delete(Projects proj)
        {
            this.database.Projects.Remove(proj);
            this.database.SaveChanges();
        }


        public List<Projects> GetByCustomer(Guid id)
        {
            return this.database.Projects.Where(g => g.Customer_ID == id).ToList();
        }

    }
}

Projet_ELMOHCINE_EZZERRIFI/Controllers/PoleController.cs
using Projet_ELMOHCINE_EZZERRIFI.Models;
using Projet_ELMOHCINE_EZZERRIFI.Models.Employee;
using Projet_ELMOHCINE_EZZERRIFI.Models.Pole;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projet_ELMOHCINE_EZZERRIFI.Controllers
{
    public class PoleController : Controller
    {
        public ActionResult List()
        {
            using (var dao= new NotesDeFraisEntities2() )
            {
                PoleRepository PoleRepo = new PoleRepository(dao);
                EmployeeRepository EmpRepo = new EmployeeRepository(dao);

                IEnumerable<PoleModel> polesWithoutManager = from g in PoleRepo.GetAll() select new PoleModel(g);

                List<PoleModel> poles = new List<PoleModel>();
                foreach(var pole in polesWithoutManager)
                {
                    pole.Manager = new EmployeeModel(EmpRepo.GetById(pole.Manager_ID));
                    poles.Add(pole);
                }

                return View("List", poles);
            }
        }

        public ActionResult Create()
        {
            using (var dao = new NotesDeFraisEntities2())
            {
                EmployeeRepository EmpRepo = new EmployeeRepository(dao);


                IEnumerable<EmployeeModel> employees = from g in EmpRepo.GetAll() select new EmployeeModel(g);
                ViewData["Employee"] = employees.Where(g => g.Role.Name == "Manageur");

            }
            return View("Create");
        }

        public ActionResult CreateAction(PoleModel pole)
        {
            using(var dao = new NotesDeFraisEntities2())
            {
                PoleRepository PoleRepo = new PoleRepository(dao);


                Poles p = new Poles();
                p.Name = pole.Name;
                p.Manager_ID = pole.Manager_ID;


                PoleRepo.Add(p);
            }


            return RedirectToAction("List");
        }

        public ActionResult Edit(Guid id)
        {
            using (var dao = new NotesDeFraisEntities2())
            {
                EmployeeRepository EmpRepo = new EmployeeRepository(dao);
                PoleRepository PoleRepo = new PoleRepository(dao);

                IEnumerable<EmployeeModel> employees = from g in EmpRepo.GetAll() select new EmployeeModel(g);
                ViewData["Employee"] = employees.Where(g => g.Role.Name == "Manageur");

                return View("Edit", new PoleModel(PoleRepo.GetById(id)));
            }
        }

        public ActionResult EditAction(PoleModel Pole)
        {

            using(var dao = new NotesDeFraisEntities2())
            {
                PoleRepository PoleRepo = new PoleRepository(dao);

                Poles pole = new Poles();

                pole.Pole_ID = Pole.Pole_ID;
                pole.Name = Pole.Name;
                pole.Manager_ID = Pole.Manager_ID;

                PoleRepo.Edit(pole);
            }
            return RedirectToAction("List");
        }

        public ActionResult Details(Guid id)
        {
            using(var dao = new NotesDeFraisEntities2())
            {
                PoleRepository PoleRepo = new PoleRepository(dao);

                PoleModel pole = new PoleModel(PoleRepo.GetById(id));

                return View("Details", pole);
            }
        }


    }
}

Projet_ELMOHCINE_EZZERRIFI/Controllers/ProjetController.cs
using Projet_ELMOHCINE_EZZERRIFI.Models;
using Projet_ELMOHCINE_EZZERRIFI.Models.Client;
using Projet_ELMOHCINE_EZZERRIFI.Models.Pole;
using Projet_ELMOHCINE_EZZERRIFI.Models.Projet;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projet_ELMOHCINE_EZZERRIFI.Controllers
{
    public class ProjetController : Controller
    {
        public ActionResult List()
        {

            using(var dao = new NotesDeFraisEntities2())
            {
                ProjetRepository ProjRepo = new ProjetRepository(dao);
                PoleRepository PoleRepo = new PoleRepository(dao);

                IEnumerable<ProjetModel> ListProj = from g in ProjRepo.GetAll() select new ProjetModel(g);
                ListProj = ListProj.ToList();

                foreach (var i in ListProj)
                {
                    i.Poles = new PoleModel(PoleRepo.GetById(i.Pole_ID));
                }


                return View("List",ListProj);
            }

        }
        public ActionResult Create()
        {
            using(var dao = new NotesDeFraisEntities2())
            {
                PoleRepository PoleRepo = new PoleRepository(dao);
                ClientRepository CustRepo = new ClientRepository(dao);

                ViewData["poles"] = from g in PoleRepo.GetAll() select new PoleModel(g);
                ViewData["clients"] = from g in CustRepo.GetAll() select new ClientModel(g);

            }
            return View("Create");
        }

        [HttpPost]
        public ActionResult CreateAction(ProjetModel projet)
        {
            using (var dao = new NotesDeFraisEntities2())
            {
                ProjetRepository ProjRepo = new ProjetRepository(dao);
                PoleRepository PoleRepo = new PoleRepository(dao);
                ClientRepository CustRepo = new ClientRepository(dao);

                Projects entite = new Projects();

                entite.Project_ID = Guid.NewGuid();
                entite.Name = projet.Name;
                entite.Description = projet.Description;
                entite.Budget = projet.Budget;
                entite.Customer_ID = projet.Customer_ID;
                entite.Pole_ID = projet.Pole_ID;

                entite.Customers = CustRepo.GetById(projet.Customer_ID);
                entite.Poles = PoleRepo.GetById(projet.Pole_ID);

                ProjRepo.Add(entite);

            }
            return RedirectToAction("List");
        }


        public ActionResult Delete(Guid id)
        {
            using(var dao = new NotesDeFraisEntities2())
            {
                ProjetRepository ProjRepo = new ProjetRepository(dao);

                ProjRepo.Delete(ProjRepo.GetById(id));

            }

            return RedirectToAction("List");
        }


    }
}

Projet_ELMOHCINE_EZZERRIFI/Views/Projet/Create.cshtml
@model Projet_ELMOHCINE_EZZERRIFI.Models.Projet.ProjetModel

@{
    ViewBag.Title = "Create";
}

<h2>Nouveau projet</h2>

@using (Html.BeginForm("CreateAction", "Projet",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Budget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Budget, new { htmlAttributes = new { @class = "form-control" }, type ="number" })
                @Html.ValidationMessageFor(model => model.Budget, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="Customer_ID" id="Customer_ID" class="form-control">
                    @foreach (var client in ViewBag.clients)
                    {
                        <option value="@client.Customer_ID">@client.Name</option>
                    }
                </select>
                @Html.ActionLink("+ Nouveau client","Create","Client")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pole_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="Pole_ID" id="Pole_ID" class="form-control">
                    @foreach(var pole in ViewBag.poles)
                    {
                        <option value="@pole.Pole_ID">@pole.Name</option>
                    }
                </select>
                @Html.ActionLink("+ Nouveau pôle", "Create", "Pole")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la list", "List")
</div>

Projet_ELMOHCINE_EZZERRIFI/Views/Projet/List.cshtml
@model IEnumerable<Projet_ELMOHCINE_EZZERRIFI.Models.Projet.ProjetModel>

@{
    ViewBag.Title = "List";
}

<h2>List des projets</h2>

<p>
    @Html.ActionLink("Nouveau projet", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Budget)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pole_ID)
        </th>
        <!--th>
            @Html.DisplayNameFor(model => model.Expanses)
        </th-->
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Budget)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Client.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Poles.Name)
        </td>
        <!--td>
            @if(item.Expanses != null)
            {
                foreach(var expanse in item.Expanses)
                {
                    <text>- </text> @expanse.Amount_TTC
                        if(expanse.Expanse_ID != item.Expanses.Last().Expanse_ID){ <br />}
                }
            }
            else
            {
                @Html.ActionLink("+ Nouvelle expanse","Create","Expanse")
            }

        </td-->
        <td>
            @Html.ActionLink("Détails", "Details", new { @item.Project_ID  }) |
            @Html.ActionLink("Edit", "Edit", new { @item.Project_ID  }) |
            <a onclick="return (confirm('Etes-vous sûr de vouloir supprimer cet élément ?'));" href="Delete/@item.Project_ID">Supprimer</a>
        </td>
    </tr>
}

</table>